### ISSUE TITLE
Improve video resilience

### ISSUE THREAD

**Issue by HugoGresse** [Instant-Visio/InstantVisio-WebApp#148]
# Constated issue
- brave browser: we can join and enable video but no video feed will be displayed on the brower (at least on mobile), possibly because fingerprinting has been disable or come request is blocked due to the ad blocker

# Possible issue:
- port are blocked for outgoing request on user nerwork (the doc says that : 
    > For optimal performance firewalls should be configured to allow UDP hole punching and outgoing UDP on the following ports:
    3478 (for signaling and media tunnelling, where necessary)
    50000 and 65534 (for direct peer-to-peer media connections)

**Comment by stephanelucon** [comment]
We have several tools to provide a one click webRTC room experience :
1. firebase function [**ACTIVE SOLUTION**] creates a daily room through daily API .
Pro: significant support from daily, P2P
Contra: P2P means more CPU pressure + fast decreasing perfs on 2+ calls
Solution: in touch with daily about using hosted rooms instead of P2P

2. Implement Twilio API
Pro: significant support from Twilio, documentation and demo apps available
Contra: new work from scratch

3. create a JITSI room through the existing & available HDS server from Jérôme Pansatel
pro : immediately available, no download
contra : dimensioning? Custo UI?

4. implement a switch between main UX and a safe-mode with less advanced UI (ex: Jérôme's server).
pro: immediate fall back solution(s) for users
contra: multiple UX scenario, no crisp support unless we customize UI on the fallback server

**Comment by HugoGresse** [comment]
Twilio will probably help, will see in the future, in the meantime, I'm closing this.
